### PR TITLE
Created german translation

### PR DESCRIPTION
**Pull request by MasterZelgadis**
Hi, I created a german translation

### CODE REVIEW

**Comment by vigoren** [comment]
Oh this is awesome! Thanks so much for doing that.

I am planning on a release with a few bug fixes in the next day or 2 so I will definitely add this into that release.

**Comment by vigoren** [comment]
Hate to do this but I had to add a couple more keys to the language file. Would it be possible for you to add them into your translated file?

```
"FSC.HourShorthand": "hr",
"FSC.MinuteShorthand": "min",
"FSC.SecondShorthand": "sec",
"FSC.SetCurrentDateDialog.Title": "Confirm Current Date Change",
"FSC.SetCurrentDateDialog.Content": "You have selected to change the date to a day which is not currently visible!<br/>Are you sure you want to change the current date to <strong>{DATE}</strong>?",
```

Thank you again for doing this work :)

**Comment by MasterZelgadis** [comment]
Yep, will do it tomorrow

**Comment by MasterZelgadis** [comment]
Ok added the translations to the de.json

**Comment by vigoren** [comment]
Thanks so much for the translations

**Pull request merged**
